CREATE TABLE DEPT(
DEPARTMENTID INT PRIMARY KEY,
DEPARTMENTNAME VARCHAR(100) NOT NULL UNIQUE,
DEPARTMENTCODE VARCHAR(50) NOT NULL UNIQUE,
LOCATION VARCHAR(50) NOT NULL
)
INSERT INTO DEPT VALUES
(1,'ADMIN','ADM','A-BLOCK'),
(2,'COMPUTER','CE','C-BLOCK'),
(3,'CIVIL','CI','G-BLOCK'),
(4,'ELECTRICAL','EE','E-BLOCK'),
(5,'MECHENICAL','ME','B-BLOCK')

CREATE TABLE PERSON
(
PERSONID INT PRIMARY KEY,
PERSONNAME VARCHAR(100) NOT NULL,
DEPARTMENTID INT FOREIGN KEY REFERENCES DEPT(DEPARTMENTID),
SALARY DECIMAL(8,2) NOT NULL,
JOININGDATE DATETIME NOT NULL,
CITY VARCHAR(100) NOT NULL
)
INSERT INTO PERSON VALUES
(101,'RAHUL TRIPATHI',2,56000,'2000-01-01','RAJKOT'),
(102,'Hardik Pandya ',3,18000,'2001-09-25','AHMEDABAD'),
(103,'Bhavin Kanani ',4,25000,'2000-05-14','BARODA'),
(104,'BHOOMI VAISHNAV',1,39000,'2005-02-08','RAJKOT'),
(105,'ROHIT TOPIYA',2,17000,'2001-07-23','JAMNAGAR'),
(106,'PRIYA MENPARA',NULL,9000,'2000-10-18','AHMEDABAD'),
(107,'NEHA SHARMA',2,34000,'2002-12-25','RAJKOT'),
(108,'NAYAN GOSWAMI',3,25000,'2001-07-01','RAJKOT'),
(109,'Mehul Bhundiya ',4,13500,'2005-01-09','BARODA'),
(110,' Mohit Maru ',5,14000,'2000-05-25','JAMNAGAR')

--Part – A: 
--1. Combine information from Person and Department table using cross join or Cartesian product. 
	SELECT *
	FROM PERSON CROSS JOIN DEPT

	
--2. Find all persons with their department name 
	SELECT PERSONNAME, DEPARTMENTNAME
	FROM PERSON
	INNER JOIN DEPT
	ON PERSON.DEPARTMENTID=DEPT.DEPARTMENTID

--3. Find all persons with their department name & code. 
	SELECT PERSONNAME,DEPARTMENTNAME,DEPARTMENTCODE
	FROM PERSON
	INNER JOIN DEPT
	ON PERSON.DEPARTMENTID=DEPT.DEPARTMENTID

--4. Find all persons with their department code and location. 
	SELECT PERSONNAME, DEPARTMENTCODE,LOCATION
	FROM PERSON
	INNER JOIN DEPT
	ON PERSON.DEPARTMENTID=DEPT.DEPARTMENTID

--5. Find the detail of the person who belongs to Mechanical department. 
	SELECT *
	FROM PERSON
	INNER JOIN DEPT
	ON PERSON.DEPARTMENTID=DEPT.DEPARTMENTID
	WHERE DEPARTMENTNAME = 'MECHENICAL'

--6. Final person’s name, department code and salary who lives in Ahmedabad city.
	SELECT PERSONNAME,DEPARTMENTCODE,SALARY
	FROM PERSON
	INNER JOIN DEPT
	ON PERSON.DEPARTMENTID=DEPT.DEPARTMENTID
	WHERE CITY = 'AHMEDABAD'

--7. Find the person's name whose department is in C-Block. 
	SELECT PERSONNAME
	FROM PERSON
	INNER JOIN DEPT
	ON PERSON.DEPARTMENTID=DEPT.DEPARTMENTID
	WHERE LOCATION = 'C-BLOCK'

--8. Retrieve person name, salary & department name who belongs to Jamnagar city. 
	SELECT PERSONNAME,SALARY,DEPARTMENTNAME
	FROM PERSON
	INNER JOIN DEPT
	ON PERSON.DEPARTMENTID=DEPT.DEPARTMENTID
	WHERE CITY = 'JAMNAGAR'

--9. Retrieve person’s detail who joined the Civil department after 1-Aug-2001. 
	SELECT *
	FROM PERSON
	INNER JOIN DEPT
	ON PERSON.DEPARTMENTID=DEPT.DEPARTMENTID
	WHERE DEPARTMENTNAME = 'CIVIL' AND JOININGDATE > '2001-08-01'

--10. Display all the person's name with the department whose joining date difference with the current date is more than 365 days.
	SELECT PERSONNAME,DEPARTMENTNAME,JOININGDATE
	FROM PERSON
	INNER JOIN DEPT
	ON PERSON.DEPARTMENTID=DEPT.DEPARTMENTID
	WHERE DATEDIFF(DAY,JOININGDATE,GETDATE()) > 365

--11. Find department wise person counts. 
	SELECT DEPARTMENTNAME,COUNT(DEPT.DEPARTMENTID)
	FROM PERSON
	INNER JOIN DEPT
	ON PERSON.DEPARTMENTID=DEPT.DEPARTMENTID
	GROUP BY DEPARTMENTNAME
	
--12. Give department wise maximum & minimum salary with department name.
	SELECT DEPARTMENTNAME,MAX(SALARY) AS MAX_SALARY,MIN(SALARY) AS MIN_SALARY
	FROM PERSON
	INNER JOIN DEPT
	ON PERSON.DEPARTMENTID=DEPT.DEPARTMENTID
	GROUP BY DEPARTMENTNAME
	
--13. Find city wise total, average, maximum and minimum salary. 
	SELECT CITY,MAX(SALARY) AS MAX_SALARY,MIN(SALARY) AS MIN_SALARY,AVG(SALARY) AS AVG_SALARY
	FROM PERSON
	INNER JOIN DEPT
	ON PERSON.DEPARTMENTID=DEPT.DEPARTMENTID
	GROUP BY CITY

--14. Find the average salary of a person who belongs to Ahmedabad city. 
	SELECT CITY, AVG(SALARY) AS AVG_SALARY
	FROM PERSON
	INNER JOIN DEPT
	ON PERSON.DEPARTMENTID=DEPT.DEPARTMENTID
	WHERE CITY = 'AHMEDABAD'
	GROUP BY CITY

--15. Produce Output Like: <PersonName> lives in <City> and works in <DepartmentName> Department. (In single column) 
	SELECT PERSON.PERSONNAME + ' LIVES IN '+ CITY + ' WORKS IN ' + DEPARTMENTNAME + ' DEPARTMENT'
	FROM PERSON
	INNER JOIN DEPT
	ON PERSON.DEPARTMENTID=DEPT.DEPARTMENTID

--Part – B: 
--1. Produce Output Like: <PersonName> earns <Salary> from <DepartmentName> department monthly. (In single column) 
	SELECT PERSONNAME + ' EARNS ' +  CAST(SALARY AS VARCHAR(10))+' FROM '+ DEPARTMENTNAME  + ' DEPARTMENT MONTHLY'
	FROM PERSON
	JOIN DEPT
	ON PERSON.DEPARTMENTID=DEPT.DEPARTMENTID
	

--2. Find city & department wise total, average & maximum salaries.
		SELECT CITY , DEPARTMENTNAME, SUM(SALARY) AS TOTAL , MAX(SALARY) AS MAX_SALARY , MIN(SALARY) AS MIN_SALARY
		FROM PERSON
		JOIN DEPT
		ON PERSON.DEPARTMENTID=DEPT.DEPARTMENTID
		GROUP BY CITY , DEPARTMENTNAME

--3. Find all persons who do not belong to any department.
	SELECT PERSONNAME
	FROM PERSON
	FULL OUTER JOIN DEPT
	ON PERSON.DEPARTMENTID=DEPT.DEPARTMENTID
	WHERE DEPT.DEPARTMENTID IS NULL
	
--4. Find all departments whose total salary is exceeding 100000.
	SELECT DEPARTMENTNAME
	FROM PERSON
	JOIN DEPT
	ON PERSON.DEPARTMENTID=DEPT.DEPARTMENTID
	GROUP BY DEPARTMENTNAME
	HAVING SUM(SALARY) > 10000

--Part – C: 
--1. List all departments who have no person. 
	SELECT DEPARTMENTNAME
	FROM PERSON
	JOIN DEPT
	ON PERSON.DEPARTMENTID=DEPT.DEPARTMENTID
	GROUP BY DEPARTMENTNAME
	HAVING COUNT(DEPT.DEPARTMENTID) = 0

--2. List out department names in which more than two persons are working. 
	SELECT DEPARTMENTNAME
	FROM PERSON
	JOIN DEPT
	ON PERSON.DEPARTMENTID=DEPT.DEPARTMENTID
	GROUP BY DEPARTMENTNAME
	HAVING COUNT(DEPT.DEPARTMENTID) > 2
	
--3. Give a 10% increment in the computer department employee’s salary. (Use Update) 
	UPDATE PERSON
	SET SALARY = SALARY + (SALARY * 0.1)
	FROM PERSON
	JOIN DEPT
	ON PERSON.DEPARTMENTID=DEPT.DEPARTMENTID
	
	

